# Generated by Django 2.1.7 on 2019-03-26 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remise_pourcentage', models.IntegerField()),
                ('remise_montant', models.IntegerField()),
                ('date', models.DateField()),
                ('salle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='mode_de_payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='salles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('diminutif', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='usersGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb.usersGroup'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='salles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb.salles'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb.users'),
        ),
        migrations.AddField(
            model_name='image',
            name='salles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb.salles'),
        ),
        migrations.AddField(
            model_name='facture',
            name='mode_de_payement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb.mode_de_payement'),
        ),
        migrations.AddField(
            model_name='facture',
            name='reservations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airbnb.reservations'),
        ),
    ]
